foods_urls = [
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/qtela.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/lays.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/jetz.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/chiki.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/chitato.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/cheetos.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/doritos.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-ringan-biskuit/canasta.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-berserat/satelit-agar-agar.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-berserat/govit.html",
    "https://www.idmarco.com/grosir-makanan-murah/makanan-berserat/gowell.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/buburia.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/indomie.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/chef-cuisine.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/mie-telor-cap-3-ayam.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/pop-mie.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/sarimi.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/supermie.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/nissin.html",
    "https://www.idmarco.com/grosir-makanan-murah/mie/sakura.html",
    "https://www.idmarco.com/grosir-makanan-murah/biskuit/wonderland.html",
    "https://www.idmarco.com/grosir-makanan-murah/biskuit/dueto.html",
    "https://www.idmarco.com/grosir-makanan-murah/biskuit/trenz.html",
    "https://www.idmarco.com/grosir-makanan-murah/biskuit/inti-gandum.html",
]

beverages_urls = [
    "https://www.idmarco.com/grosir-minuman-murah/instant/sedap-wangi.html",
    "https://www.idmarco.com/grosir-minuman-murah/instant/kahuripan.html",
    "https://www.idmarco.com/grosir-minuman-murah/sirup/sirup-indofood.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/kopi-dan-teh/cafela.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/kopi-dan-teh/ichi-ocha.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/minuman-rasa/frutamin.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/soft-drink/pepsi.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/soft-drink/sting.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/kental-manis/indomilk.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/kental-manis/cap-enaak.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/kental-manis/tiga-sapi.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/kental-manis/kremer.html",
    "https://www.idmarco.com/grosir-minuman-murah/minuman-ringan/air-minum-kemasan/club.html",
    "https://www.idmarco.com/grosir-minuman-murah/susu/susu-cair-dan-susu-kental/milkuat.html",
    "https://www.idmarco.com/grosir-minuman-murah/susu/susu-cair-dan-susu-kental/indomilk.html",
    "https://www.idmarco.com/grosir-minuman-murah/susu/susu-bubuk/indomilk.html",
]

household_urls = [
    "https://www.idmarco.com/grosir-kebutuhan-rumah-tangga-murah/deterjen-sabun-dan-pewangi/total.html",
    "https://www.idmarco.com/grosir-kebutuhan-rumah-tangga-murah/deterjen-sabun-dan-pewangi/bukrim.html",
    "https://www.idmarco.com/grosir-kebutuhan-rumah-tangga-murah/alat-kebersihan/scotch-brite.html",
    "https://www.idmarco.com/grosir-kebutuhan-rumah-tangga-murah/pembersih-lantai/kliny.html",
    "https://www.idmarco.com/grosir-kebutuhan-rumah-tangga-murah/sabun-cuci-piring/bukrim-liquish.html",
    "https://www.idmarco.com/grosir-kebutuhan-rumah-tangga-murah/sabun-cuci-piring/total.html",
]

ingredients_urls = [
    "https://www.idmarco.com/grosir-bahan-masak-murah/kecap/kecap-indofood.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/saus/sambal-indofood.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/saus/saus-tomat-indofood.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/bumbu/maggi.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/bumbu/bumbu-indofood.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/terigu/cakra-kembar.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/terigu/kunci-biru.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/terigu/segitiga-biru.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/terigu/chesa.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/terigu/lencana-merah.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/garam/garam-refina.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/minyak-goreng/palmia.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/minyak-goreng/happy-salad-oil.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/minyak-goreng/bimolli.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/mentega/palmia.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/mentega/orchid-butter.html",
    "https://www.idmarco.com/grosir-bahan-masak-murah/mentega/amanda.html",
]

healthbeauty_urls = [
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/pembalut-wanita/charm.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/popok-dewasa/lifree.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-rambut/aishaderm.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-rambut/natasha.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-tubuh/aishaderm.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-tubuh/bio-karpela.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-tubuh/natasha.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-wajah/aishaderm.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-wajah/bio-karpela.html",
    "https://www.idmarco.com/grosir-produk-kesehatan-murah/perawatan-wajah/natasha.html",
]

babymother_urls = [
    "https://www.idmarco.com/grosir-keperluan-ibu-dan-anak-murah/susu-ibu-hamil-dan-menyusui/sun.html",
    "https://www.idmarco.com/grosir-keperluan-ibu-dan-anak-murah/popok-bayi/popok-celana/genki-moko-moko.html",
    "https://www.idmarco.com/grosir-keperluan-ibu-dan-anak-murah/makanan-bayi/promina.html",
    "https://www.idmarco.com/grosir-keperluan-ibu-dan-anak-murah/makanan-bayi/sun.html",
]